const nome = 'ELVIRA';
const sobrenome = 'NOVAKOWSKI';
const idade = 19;
const peso = 53;
const alturaEmM = 1.61;
let imc;
let anodenascimento;
imc = peso / (alturaEmM * alturaEmM);
anodenascimento = 2021 - idade;
console.log(`${nome} ${sobrenome} tem ${idade} anos, pesa ${peso} kg`);
console.log(`tem ${alturaEmM} de altura e seu IMC é de ${imc}`);
console.log(`${nome} nasceu em ${anodenascimento}.`);